version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: servihub_postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: servihub_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
